name: C++ CMake Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++

    - name: Create build directory
      run: mkdir build

    - name: Run CMake
      run: cmake -S . -B build

    - name: Build the project
      run: cmake --build build

    - name: Make test scripts executable
      run: chmod +x ../tests/*.sh
      working-directory: build

    - name: Run hello_github script
      working-directory: build
      run: ../tests/test.sh

    - name: Run vector script
      working-directory: build
      run: ../tests/vecTest.sh
